### PR TITLE
[CO-240] Add basic tests.

### PR DESCRIPTION
**Pull request by davidewatson**

### CODE REVIEW

**Comment by davidewatson** [comment]
This fails tests due to resource limitation of our CI cluster and should be merged anyway since the new cmc is a ways out.

**Comment by mikeln** [comment]
Yes, but the "helm tests" should be done in the "leaf charts".  vs, this chart which pulls everything together should have "integration tests" instead.

**Comment by davidewatson** [comment]
I agree that the tests in this chart are integration tests. That doesn't prevent them from being implemented as either a `helm test` or using the pipeline mechanism. Both will work in this case.

Since the existing tests were `helm tests` I think they should remain `helm test` for this sprint. Is there a reason you think they should use the pipeline mechanism instead?

**Comment by davidewatson** [comment]
These tests will not pass on a cluster which already has logging deployed because we do not properly name our Cluster scoped resources. This causes the helm deployment to fail. We'll need to revisit this in another sprint.

**Comment by davidewatson** [comment]
OBE

**Pull request closed without merging**
